#include <sokol_app.h>
#include <sokol_gfx.h>
#include <new>

sapp_touchpoint& (sapp_touchpoint::*_0)(sapp_touchpoint&&) = &sapp_touchpoint::operator=;
sapp_event& (sapp_event::*_1)(sapp_event&&) = &sapp_event::operator=;
sapp_range& (sapp_range::*_2)(sapp_range&&) = &sapp_range::operator=;
sapp_image_desc& (sapp_image_desc::*_3)(sapp_image_desc&&) = &sapp_image_desc::operator=;
sapp_icon_desc& (sapp_icon_desc::*_4)(sapp_icon_desc&&) = &sapp_icon_desc::operator=;
sapp_allocator& (sapp_allocator::*_5)(sapp_allocator&&) = &sapp_allocator::operator=;
sapp_desc& (sapp_desc::*_6)(sapp_desc&&) = &sapp_desc::operator=;
sapp_html5_fetch_response& (sapp_html5_fetch_response::*_7)(sapp_html5_fetch_response&&) = &sapp_html5_fetch_response::operator=;
sapp_html5_fetch_request& (sapp_html5_fetch_request::*_8)(sapp_html5_fetch_request&&) = &sapp_html5_fetch_request::operator=;
void (*_9)(const sapp_desc&) = &::sapp_run;
sg_buffer& (sg_buffer::*_10)(sg_buffer&&) = &sg_buffer::operator=;
sg_image& (sg_image::*_11)(sg_image&&) = &sg_image::operator=;
sg_shader& (sg_shader::*_12)(sg_shader&&) = &sg_shader::operator=;
sg_pipeline& (sg_pipeline::*_13)(sg_pipeline&&) = &sg_pipeline::operator=;
sg_pass& (sg_pass::*_14)(sg_pass&&) = &sg_pass::operator=;
sg_context& (sg_context::*_15)(sg_context&&) = &sg_context::operator=;
sg_range& (sg_range::*_16)(sg_range&&) = &sg_range::operator=;
sg_color& (sg_color::*_17)(sg_color&&) = &sg_color::operator=;
sg_pixelformat_info& (sg_pixelformat_info::*_18)(sg_pixelformat_info&&) = &sg_pixelformat_info::operator=;
sg_features& (sg_features::*_19)(sg_features&&) = &sg_features::operator=;
sg_limits& (sg_limits::*_20)(sg_limits&&) = &sg_limits::operator=;
sg_color_attachment_action& (sg_color_attachment_action::*_21)(sg_color_attachment_action&&) = &sg_color_attachment_action::operator=;
sg_depth_attachment_action& (sg_depth_attachment_action::*_22)(sg_depth_attachment_action&&) = &sg_depth_attachment_action::operator=;
sg_stencil_attachment_action& (sg_stencil_attachment_action::*_23)(sg_stencil_attachment_action&&) = &sg_stencil_attachment_action::operator=;
sg_pass_action& (sg_pass_action::*_24)(sg_pass_action&&) = &sg_pass_action::operator=;
sg_bindings& (sg_bindings::*_25)(sg_bindings&&) = &sg_bindings::operator=;
sg_buffer_desc& (sg_buffer_desc::*_26)(sg_buffer_desc&&) = &sg_buffer_desc::operator=;
sg_image_data& (sg_image_data::*_27)(sg_image_data&&) = &sg_image_data::operator=;
sg_image_desc& (sg_image_desc::*_28)(sg_image_desc&&) = &sg_image_desc::operator=;
sg_shader_attr_desc& (sg_shader_attr_desc::*_29)(sg_shader_attr_desc&&) = &sg_shader_attr_desc::operator=;
sg_shader_uniform_desc& (sg_shader_uniform_desc::*_30)(sg_shader_uniform_desc&&) = &sg_shader_uniform_desc::operator=;
sg_shader_uniform_block_desc& (sg_shader_uniform_block_desc::*_31)(sg_shader_uniform_block_desc&&) = &sg_shader_uniform_block_desc::operator=;
sg_shader_image_desc& (sg_shader_image_desc::*_32)(sg_shader_image_desc&&) = &sg_shader_image_desc::operator=;
sg_shader_stage_desc& (sg_shader_stage_desc::*_33)(sg_shader_stage_desc&&) = &sg_shader_stage_desc::operator=;
sg_shader_desc& (sg_shader_desc::*_34)(sg_shader_desc&&) = &sg_shader_desc::operator=;
sg_buffer_layout_desc& (sg_buffer_layout_desc::*_35)(sg_buffer_layout_desc&&) = &sg_buffer_layout_desc::operator=;
sg_vertex_attr_desc& (sg_vertex_attr_desc::*_36)(sg_vertex_attr_desc&&) = &sg_vertex_attr_desc::operator=;
sg_layout_desc& (sg_layout_desc::*_37)(sg_layout_desc&&) = &sg_layout_desc::operator=;
sg_stencil_face_state& (sg_stencil_face_state::*_38)(sg_stencil_face_state&&) = &sg_stencil_face_state::operator=;
sg_stencil_state& (sg_stencil_state::*_39)(sg_stencil_state&&) = &sg_stencil_state::operator=;
sg_depth_state& (sg_depth_state::*_40)(sg_depth_state&&) = &sg_depth_state::operator=;
sg_blend_state& (sg_blend_state::*_41)(sg_blend_state&&) = &sg_blend_state::operator=;
sg_color_state& (sg_color_state::*_42)(sg_color_state&&) = &sg_color_state::operator=;
sg_pipeline_desc& (sg_pipeline_desc::*_43)(sg_pipeline_desc&&) = &sg_pipeline_desc::operator=;
sg_pass_attachment_desc& (sg_pass_attachment_desc::*_44)(sg_pass_attachment_desc&&) = &sg_pass_attachment_desc::operator=;
sg_pass_desc& (sg_pass_desc::*_45)(sg_pass_desc&&) = &sg_pass_desc::operator=;
sg_trace_hooks& (sg_trace_hooks::*_46)(sg_trace_hooks&&) = &sg_trace_hooks::operator=;
sg_slot_info& (sg_slot_info::*_47)(sg_slot_info&&) = &sg_slot_info::operator=;
sg_buffer_info& (sg_buffer_info::*_48)(sg_buffer_info&&) = &sg_buffer_info::operator=;
sg_image_info& (sg_image_info::*_49)(sg_image_info&&) = &sg_image_info::operator=;
sg_shader_info& (sg_shader_info::*_50)(sg_shader_info&&) = &sg_shader_info::operator=;
sg_pipeline_info& (sg_pipeline_info::*_51)(sg_pipeline_info&&) = &sg_pipeline_info::operator=;
sg_pass_info& (sg_pass_info::*_52)(sg_pass_info&&) = &sg_pass_info::operator=;
sg_gl_context_desc& (sg_gl_context_desc::*_53)(sg_gl_context_desc&&) = &sg_gl_context_desc::operator=;
sg_metal_context_desc& (sg_metal_context_desc::*_54)(sg_metal_context_desc&&) = &sg_metal_context_desc::operator=;
sg_d3d11_context_desc& (sg_d3d11_context_desc::*_55)(sg_d3d11_context_desc&&) = &sg_d3d11_context_desc::operator=;
sg_wgpu_context_desc& (sg_wgpu_context_desc::*_56)(sg_wgpu_context_desc&&) = &sg_wgpu_context_desc::operator=;
sg_context_desc& (sg_context_desc::*_57)(sg_context_desc&&) = &sg_context_desc::operator=;
sg_allocator& (sg_allocator::*_58)(sg_allocator&&) = &sg_allocator::operator=;
sg_desc& (sg_desc::*_59)(sg_desc&&) = &sg_desc::operator=;
void (*_60)(const sg_desc&) = &::sg_setup;
sg_buffer (*_61)(const sg_buffer_desc&) = &::sg_make_buffer;
sg_image (*_62)(const sg_image_desc&) = &::sg_make_image;
sg_shader (*_63)(const sg_shader_desc&) = &::sg_make_shader;
sg_pipeline (*_64)(const sg_pipeline_desc&) = &::sg_make_pipeline;
sg_pass (*_65)(const sg_pass_desc&) = &::sg_make_pass;
void (*_66)(sg_image, const sg_image_data&) = &::sg_update_image;
void (*_67)(const sg_pass_action&, int, int) = &::sg_begin_default_pass;
void (*_68)(const sg_pass_action&, float, float) = &::sg_begin_default_passf;
void (*_69)(sg_pass, const sg_pass_action&) = &::sg_begin_pass;
void (*_70)(const sg_bindings&) = &::sg_apply_bindings;
void (*_71)(sg_shader_stage, int, const sg_range&) = &::sg_apply_uniforms;
sg_buffer_desc (*_72)(const sg_buffer_desc&) = &::sg_query_buffer_defaults;
sg_image_desc (*_73)(const sg_image_desc&) = &::sg_query_image_defaults;
sg_shader_desc (*_74)(const sg_shader_desc&) = &::sg_query_shader_defaults;
sg_pipeline_desc (*_75)(const sg_pipeline_desc&) = &::sg_query_pipeline_defaults;
sg_pass_desc (*_76)(const sg_pass_desc&) = &::sg_query_pass_defaults;
void (*_77)(sg_buffer, const sg_buffer_desc&) = &::sg_init_buffer;
void (*_78)(sg_image, const sg_image_desc&) = &::sg_init_image;
void (*_79)(sg_shader, const sg_shader_desc&) = &::sg_init_shader;
void (*_80)(sg_pipeline, const sg_pipeline_desc&) = &::sg_init_pipeline;
void (*_81)(sg_pass, const sg_pass_desc&) = &::sg_init_pass;
void (*_82)(sg_buffer, const sg_range&) = &::sg_update_buffer;
int (*_83)(sg_buffer, const sg_range&) = &::sg_append_buffer;
